language: go

go:
    - 1.14.x

services:
  - postgresql

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

  env:
  - GO111MODULE=on

script:
  - make build  
  - make clean  
  - make local-e2e-test 
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
