version: '3.4'

networks:
  e2e-rest-network:

services:
  db:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - e2e-rest-network
  api:
    build:
      context: .
      target: release
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment: 
     - POSTGRES_HOST=db
    depends_on:
      - db
    command: ["wait-for-it", "db:${POSTGRES_PORT}", "-s", "--", "/app/main"]
    networks:
      - e2e-rest-network
